SUPABASE_URL = "https://zrdsilgszicjfwhwmnlz.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyZHNpbGdzemljamZ3aHdtbmx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzcwMTksImV4cCI6MjA2NTkxMzAxOX0.dDZ0rpk-vE728d_1HhFzUukDCYC6g5JZ4mwYCZHSZh0"
CLOUDINARY_CLOUD_NAME = "dxbahdnld"
CLOUDINARY_API_KEY = "461589649231377"
CLOUDINARY_API_SECRET = "DuvksEZOxHPA262b0BF285T_WAk"
SECRET_KEY = "change-this-to-a-random-secret-key"
USE_LOCAL_DB = True 